// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdQMVkmrmj1Gopwa7n_ULv4babIuRyYJE',
    appId: '1:746983928581:android:4b344d87cd2cdbce6efd6c',
    messagingSenderId: '746983928581',
    projectId: 'futa-finance',
    storageBucket: 'futa-finance.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstjlA_ahoM4yDyOas3Tc9c-FdRCeDjt4',
    appId: '1:746983928581:web:3481abb1480d46a16efd6c',
    messagingSenderId: '746983928581',
    projectId: 'futa-finance',
    authDomain: 'futa-finance.firebaseapp.com',
    storageBucket: 'futa-finance.firebasestorage.app',
  );

  // Windows デスクトップは Firebase C++ SDK 経由。web と同じ構成を流用する
  // （同一 Firebase プロジェクトなので apiKey/authDomain 等を共有）。
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDstjlA_ahoM4yDyOas3Tc9c-FdRCeDjt4',
    appId: '1:746983928581:web:3481abb1480d46a16efd6c',
    messagingSenderId: '746983928581',
    projectId: 'futa-finance',
    authDomain: 'futa-finance.firebaseapp.com',
    storageBucket: 'futa-finance.firebasestorage.app',
  );
}
